from pydantic import BaseModel
from typing import Optional
from datetime import datetime
from enum import Enum
from syntrillo.stroke_risk_score_v2.models.treatment_compliance import TreatmentCompliance

# Enums for constrained fields based on CHECK constraints in the database
class NumberOfStrokesOptions(str, Enum):
    ONE = "One"
    MULTIPLE = "Multiple"


class StrokeMechanismOptions(str, Enum):
    SMALL_VESSEL = "Small Vessel"
    LARGE_VESSEL = "Large Vessel"
    CRYPTOGENIC = "Cryptogenic"
    HYPERCOAGULABLE = "Hypercoagulable"
    STRUCTURAL = "Structural"
    CARDIOEMBOLIC = "Cardioembolic"


class LikelihoodOfTIAOptions(str, Enum):
    HIGH_LIKELIHOOD = "High Likelihood"
    TIA_NOT_LIKELY = "TIA not likely"


class AnemiaSeverityOptions(str, Enum):
    MILD = "Mild"
    SEVERE = "Severe"


class ArterialClotOccurrencesOptions(str, Enum):
    SINGLE_PRIOR_EVENT = "Single prior event"
    MULTIPLE_PRIOR_EVENTS = "Multiple prior events"


class PFOPresenceOptions(str, Enum):
    POSITIVE = "Positive"
    NEGATIVE = "Negative"
    UNKNOWN = "Unknown"


class VenousClotOccurrencesOptions(str, Enum):
    SINGLE = "Single"
    MULTIPLE = "Multiple"


class EjectionFractionOptions(str, Enum):
    LESS_THAN_OR_EQUAL_40 = "<=40%"
    GREATER_THAN_40 = ">40%"
    UNKNOWN = "Unknown"


class StenosisPercentageOptions(str, Enum):
    FIFTY_TO_SEVENTY = "50-70%"
    GREATER_THAN_SEVENTY = ">70%"
    UNKNOWN = "Unknown"


class OSASeverityOptions(str, Enum):
    MILD = "Mild"
    MODERATE = "Moderate"
    SEVERE = "Severe"
    UNKNOWN = "Unknown"


class CADTypeOptions(str, Enum):
    SYMPTOMATIC_MULTI_OR_SINGLE_VESSEL = "Symptomatic multi or single vessel"
    ASYMPTOMATIC_MULTIVESSEL = "Asymptomatic multivessel"
    ASYMPTOMATIC_SINGLE_VESSEL = "Asymptomatic single vessel"
    UNKNOWN = "Unknown"


class PhysicalInactivityLevelOptions(str, Enum):
    MILD = "Mild"
    MODERATE = "Moderate"
    SEVERE = "Severe"


class LDLLevelOptions(str, Enum):
    BORDERLINE = "Borderline"
    HIGH = "High"
    VERY_HIGH = "Very High"
    UNKNOWN = "Unknown"


class HDLLevelOptions(str, Enum):
    LOW = "Low"
    UNKNOWN = "Unknown"


class TriglyceridesLevelOptions(str, Enum):
    MODERATE = "Moderate"
    HIGH = "High"
    UNKNOWN = "Unknown"

class GenderOptions(str, Enum):
    MAN = "man"
    WOMAN = "woman"

# Main data model for SRS form response
class SRSFormResponse(BaseModel):
    # Required fields (NOT NULL in database)
    syntrillo_internal_key_patient: str
    syntrillo_internal_key_clinician: str
    created_at: datetime
    Gender: GenderOptions

    # Optional field (auto-generated by the database)
    srs_form_response_id: Optional[int] = None

    # Optional boolean fields
    HasPreviousStroke: Optional[bool] = None
    ScreenedForTIA: Optional[bool] = None
    HasPriorHeadCT: Optional[bool] = None
    ChronicInfarctPresent: Optional[bool] = None
    HistoryOfAtrialFibrillation: Optional[bool] = None
    HistoryOfIronDeficiencyAnemia: Optional[bool] = None
    HistoryOfArterialClots: Optional[bool] = None
    HistoryOfVenousClots: Optional[bool] = None
    HistoryOfCHF: Optional[bool] = None
    HistoryOfCarotidStenosis: Optional[bool] = None
    HistoryOfOSA: Optional[bool] = None
    HistoryOfCAD: Optional[bool] = None
    HistoryOfValvularHeartDisease: Optional[bool] = None
    HistoryOfCKD: Optional[bool] = None
    HistoryOfHyperlipidemia: Optional[bool] = None

    # Optional constrained string fields (using enums)
    NumberOfStrokes: Optional[NumberOfStrokesOptions] = None
    LatestStrokeMechanism: Optional[StrokeMechanismOptions] = None
    LikelihoodOfTIA: Optional[LikelihoodOfTIAOptions] = None
    TIAMechanism: Optional[StrokeMechanismOptions] = None
    ChronicInfarctMechanism: Optional[StrokeMechanismOptions] = None
    AnemiaSeverity: Optional[AnemiaSeverityOptions] = None
    ArterialClotOccurrences: Optional[ArterialClotOccurrencesOptions] = None
    PFOPresence: Optional[PFOPresenceOptions] = None
    VenousClotOccurrences: Optional[VenousClotOccurrencesOptions] = None
    EjectionFraction: Optional[EjectionFractionOptions] = None
    StenosisPercentage: Optional[StenosisPercentageOptions] = None
    OSASeverity: Optional[OSASeverityOptions] = None
    CADType: Optional[CADTypeOptions] = None


    # Lab values
    Triglycerides: Optional[float] = None
    LDL: Optional[float] = None
    HDL: Optional[float] = None
    HemoglobinA1c: Optional[float] = None
    Creatinine: Optional[float] = None

    # Categories
    LDLLevel: Optional[LDLLevelOptions] = None
    HDLLevel: Optional[HDLLevelOptions] = None
    TriglyceridesLevel: Optional[TriglyceridesLevelOptions] = None
    PhysicalInactivityLevel: Optional[PhysicalInactivityLevelOptions] = None

    # Physical In/Activity Values
    PhysicalInactivityHours: Optional[float] = None
    PhysicalActivityMinutes: Optional[float] = None

    # Optional timestamp field
    PriorCTDate: Optional[datetime] = None

    # Optional float/numeric fields
    Height: Optional[float] = None
    Weight: Optional[float] = None
    AvgSBP: Optional[float] = None
    RHR: Optional[float] = None
    BMI: Optional[float] = None

    # optional compliance fields
    compliance: Optional[TreatmentCompliance] = None