from pydantic import BaseModel
from enum import Enum
from typing import Optional

class TreatmentComplianceOptions(str, Enum):
    OPTIMIZED = "optimized"
    PARTIALLY_OPTIMIZED = "partially optimized"
    NOT_OPTIMIZED = "not optimized"


# Main data model for SRS form response
class TreatmentCompliance(BaseModel):
    # Optional field (auto-generated by the database)
    srs_form_response_id: Optional[int] = None # Foreign key to srs_form_responses table

    # Optional fields (NOT NULL in database)
    strokeCompliance: Optional[TreatmentComplianceOptions] = None
    tiaCompliance: Optional[TreatmentComplianceOptions] = None
    chronicInfarctCompliance: Optional[TreatmentComplianceOptions] = None
    atrialFibrillationCompliance: Optional[TreatmentComplianceOptions] = None
    ironDeficiencyAnemiaCompliance: Optional[TreatmentComplianceOptions] = None
    arterialClotsCompliance: Optional[TreatmentComplianceOptions] = None
    venousClotsCompliance: Optional[TreatmentComplianceOptions] = None
    chfCompliance: Optional[TreatmentComplianceOptions] = None
    carotidStenosisCompliance: Optional[TreatmentComplianceOptions] = None
    osaCompliance: Optional[TreatmentComplianceOptions] = None
    cadCompliance: Optional[TreatmentComplianceOptions] = None
    valvularHeartDiseaseCompliance: Optional[TreatmentComplianceOptions] = None
    ckdCompliance: Optional[TreatmentComplianceOptions] = None
    pfoCompliance: Optional[TreatmentComplianceOptions] = None
