SYSTOLIC_BP_HIGH_THRESHOLD = 169.0
SYSTOLIC_BP_LOW_THRESHOLD = 90.0
# DIASTOLIC_BP_THRESHOLD = 90.0
AVERAGE_SYSTOLIC_BP_THRESHOLD = 150.0

EXCLUDED_PATIENTS = ['2062877']

AVERAGE_SYSTOLIC_BP_DAYS = 3

STAGING_ENVIRONMENT = 'staging'
PRODUCTION_ENVIRONMENT = 'production'
AWS_SECRETS_MANAGER_HEALTHIE_IDS_SECRET_ARN_KEY = 'AWS_SECRETS_MANAGER_HEALTHIE_IDS_SECRET_ARN'
EXCLUDED_PATIENTS_KEY = 'EXCLUDED_PATIENTS'
MESSENGER_KEY = 'MESSENGER'
CLINICIANS_KEY = 'CLINICIANS'

# "5506353", "2802754", "7129594"
