# THRESHOLDS
SYSTOLIC_BP_HIGH_THRESHOLD = 169.0
SYSTOLIC_BP_LOW_THRESHOLD = 90.0
# DIASTOLIC_BP_THRESHOLD = 90.0
AVERAGE_SYSTOLIC_BP_THRESHOLD = 150.0

AVERAGE_SYSTOLIC_BP_DAYS = 3

# KEYS
DATE_RANGE_KEY = 'Date Range'
MEASUREMENT_COUNT_KEY = 'Measurement Count'
SYSTOLIC_BP_KEY = 'Avg SBP (mmHg)'
DBP_BP_KEY = 'Avg DBP (mmHg)'
SBP_CV_KEY = 'SBP CV (%)'
DBP_CV_KEY = 'DBP CV (%)'
SBP_SD_KEY = 'SBP SD (mmHg)'
DBP_SD_KEY = 'DBP SD (mmHg)'
PEAK_SBP_KEY = 'Peak SBP² (mmHg)'
PEAK_DBP_KEY = 'Peak DBP² (mmHg)'
LOW_SBP_KEY = 'Low SBP³ (mmHg)'
LOW_DBP_KEY = 'Low DBP³ (mmHg)'
HYPOTENSIVE_COUNT_KEY = 'Hypotensive Count⁴'

# ENVIRONMENTS
STAGING_ENVIRONMENT = 'staging'
PRODUCTION_ENVIRONMENT = 'production'

# "5506353", "2802754", "7129594"
