CPT_CODE = "99454"

# Healthie Constants
DEVICE_TRAINING_FORM_NAME = "Device Training Note"

# Candid Constants
AWS_SECRETS_MANAGER_CANDID_CREDENTIALS_SECRET_ARN_KEY = 'AWS_SECRETS_MANAGER_CANDID_CREDENTIALS_SECRET_ARN'
CANDID_CREDENTIALS_KEY = 'CANDID_CREDS'
CLIENT_ID_KEY = 'client_id'
CLIENT_SECRET_KEY = 'client_secret'
